### ISSUE TITLE
How to apply mutative/JSON patches during mutate?

### ISSUE THREAD

**Issue by ghost** [unadlib/mutability#1]
> [ _Hello and thanks for this library!_ ]

#### Would it be recommended to apply patches during mutate?

For example:

```ts
import { apply } from "mutative";
import { mutate } from "mutability";
// ...
try {
  mutate(baseState, (draft) => {
    const draft = apply(draft, patchesFromHost);
    throw new Error('error');
    draft.b.c = 2;
    return draft;
  });
} catch (e) {
  //
}
```

> [ _This is really more of a basic question for `mutative` but I think..._ ]

#### I could also do the following, is that correct?

```ts
  mutate(baseState, (draft) => {
    draft.entry = apply(draft.entry, patchesFromHost);
    throw new Error('error');
    draft.b.c = 2;
  });
```

It seems like either one of these might be a bit inefficient since the `"mutability" mutate` function already creates and applies patches.

Would you consider exporting the `"mutability" apply` function as well? _(Or would I import it from "mutability/dist/apply.js"?)_

**Comment by ghost** [comment]
I [tested this out](https://github.com/waynebloss/mutability/blob/main/test/apply.test.ts) on a fork and I see that it works.

However, I am somewhat confused about why `"mutability" apply` is needed if `"mutative" create` can already create patches without modifying the original and if `"mutative" apply` can already apply those patches?

Is it because `"mutability" apply` mutates the given state and `"mutative" apply` does not?

**Comment by ghost** [comment]
I [tested "mutative" apply](https://github.com/waynebloss/mutative/blob/main/test/apply-error.test.ts) as well and I see that I can basically reproduce what `"mutability" mutate` does there without any extra library.

So, I am wondering if I need `"mutability"` at all?

**Comment by unadlib** [comment]
hi @waynebloss , it depends on your needs. If you want to perform operations with mutable data, you should use `mutability`; otherwise, you can just use `mutative` for immutable data updates.

**Comment by ghost** [comment]
I think that I understand now. Thank you.
